---
- name: Deploy Pocket ID
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Pocket ID"
    service_dir_name: "{{ pocket_id_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/pocket-id/pocket-id/cd2e9f3a2ad753815ef8da998f9b54853d953a2a/docker-compose.yml"
    env_url: "https://raw.githubusercontent.com/pocket-id/pocket-id/4eeb06f29d984164939bf66299075efead87ee19/.env.example"
