---
- name: Deploy wger
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "wger"
    service_dir_name: "{{ wger_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/wger-project/docker/b450305f141247494b43d94ca21a900810f9ee93/docker-compose.yml"
    env_url: "https://raw.githubusercontent.com/wger-project/docker/fa56c45c2cc7d8665720d28c2ef53abfb3094215/config/prod.env"
    service_downloads:
      - url: "https://raw.githubusercontent.com/wger-project/docker/refs/heads/master/config/redis.conf"
        dest: "redis.conf"
    data_dirs:
      - "static"
      - "media"
      - "db"
      - "redis"
      - "beat"
