---
- name: Deploy Shelfmark
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Shelfmark"
    service_dir_name: "{{ shelfmark_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/calibrain/shelfmark/afeae46821ed0de5eeb543447ddec618d0514052/compose/stable/docker-compose.tor.yml"
