---
# ── General Configuration ─────────────────────────────────────────────
sso_enabled: true
domain: "npham.de"
timezone: "Europe/Berlin" # TZ identifier from https://en.wikipedia.org/wiki/List_of_tz_database_time_zones#List
data_base_dir: "/mnt/data"
backup_base_dir: "/mnt/backup"
service_base_dir: "~/services"

# ── Service Configuration ─────────────────────────────────────────────
# WARNING: modification of any ports won't work
# the only customizable port is the NextCloud port, but it's recommended to keep it untouched
services:
  # AdGuard Home
  adguard_home:
    enabled: true
    domain: "dns.{{ domain }}"
    container_name: "adguard-home"
    port: 80
  # AdventureLog
  adventure_log:
    enabled: true
    domain: "travel.{{ domain }}"
    container_names:
      frontend: "adventurelog-frontend"
      backend: "adventurelog-backend"
    ports:
      frontend: 3000
      backend: 80
  # Beszel
  beszel:
    enabled: true
    domain: "status.{{ domain }}"
    container_name: "beszel"
    port: 8090
  # Calibre Web Automated
  calibre_web_automated:
    enabled: true
    domain: "lib.{{ domain }}"
    container_name: "calibre-web-automated"
    port: 8083
  calibre_web_automated_book_downloader:
    enabled: true
    domain: "books.{{ domain }}"
    container_name: "calibre-web-automated-book-downloader"
    port: 8084
  # Ente Auth
  ente_auth:
    enabled: true
    domain: "2fa.{{ domain }}"
    container_name: "ente-web"
    port: 3003
  ente_api:
    enabled: true
    domain: "ente.{{ domain }}"
    container_name: "ente-museum"
    port: 8080
  # FreshRSS
  freshrss:
    enabled: true
    domain: "feed.{{ domain }}"
    container_name: "freshrss"
    port: 80
  # Ghostfolio
  ghostfolio:
    enabled: true
    domain: "wealth.{{ domain }}"
    container_name: "ghostfolio"
    port: 3333
  # Glance
  glance:
    enabled: true
    domain: "dash.{{ domain }}"
    container_name: "glance"
    port: 8080
  # Immich
  immich:
    enabled: true
    domain: "media.{{ domain }}"
    container_name: "immich_server"
    port: 2283
  # NextCloud
  nextcloud:
    enabled: true
    domain: "cloud.{{ domain }}"
    container_name: "nextcloud-aio-apache"
    port: 11000
  nextcloud_aio:
    enabled: true
    domain: "nextcloud-aio.{{ domain }}"
    container_name: "nextcloud-aio-mastercontainer"
    port: 8080
  # Pocket ID
  pocket_id:
    enabled: "{{ sso_enabled | bool }}"
    domain: "id.{{ domain }}"
    container_name: "pocket-id"
    port: 1411
  # Vaultwarden
  vaultwarden:
    enabled: true
    domain: "vault.{{ domain }}"
    container_name: "vaultwarden"
    port: 80
  # wger
  wger:
    enabled: false
    domain: "health.{{ domain }}"
    container_name: "wger-web"
    port: 8000
  # Yamtrack
  yamtrack:
    enabled: true
    domain: "track.{{ domain }}"
    container_name: "yamtrack"
    port: 8000
  # Zerobyte
  zerobyte:
    enabled: true
    domain: "backup.{{ domain }}"
    container_name: "zerobyte"
    port: 4096

# ── Email Configuration ───────────────────────────────────────────────
no_reply_mail: "noreply@{{ domain }}"
smtp_host: "smtp.protonmail.ch"
smtp_port: 587

# ── Backup Configuration ──────────────────────────────────────────────
restic_repository: "rclone:onedrive:raspberry-pi-5-backup"
rclone_arch: "arm64"
rclone_configs:
  - name: "onedrive"
    properties:
      type: "onedrive"
      token: " {{ rclone_onedrive_token }}"
      drive_id: "{{ rclone_onedrive_drive_id }}"
      drive_type: "personal"
  # - name: "proton-drive"
  #   properties:
  #     type: "protondrive"
  #     username: "{{ rclone_proton_username }}"
  #     password: "{{ rclone_proton_password }}"
  #     client_uid: "{{ rclone_proton_client_uid }}"
  #     client_access_token: "{{ rclone_proton_client_access_token }}"
  #     client_refresh_token: "{{ rclone_proton_client_refresh_token }}"
  #     client_salted_key_pass: "{{ rclone_proton_client_salted_key_pass }}"
