---
- name: Deploy AdventureLog
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "AdventureLog"
    service_dir_name: "{{ adventure_log_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/seanmorley15/AdventureLog/19baf6ab351430395f0d5167fe8d667c364fcd34/docker-compose.yml"
    env_url: "https://raw.githubusercontent.com/seanmorley15/AdventureLog/c39ff2449eb2bfefd6b3b87a31f697309ce2560f/.env.example"
