---
- name: Deploy Yamtrack
  ansible.builtin.include_role:
    name: service_deploy
  vars:
    service_name: "Yamtrack"
    service_dir_name: "{{ yamtrack_dir_name }}"
    compose_url: "https://raw.githubusercontent.com/FuzzyGrim/Yamtrack/4a5abba1f211883fa1c76865838ff218f3ebbd83/docker-compose.yml"
