---
service_dir: "{{ service_base_dir }}/{{ service_dir_name }}"
data_dir: "{{ data_base_dir }}/{{ service_dir_name }}"
backup_dir: "{{ backup_base_dir }}/{{ service_dir_name }}"
temp_backup_dir: "{{ backup_dir }}_temp"
dump_path: "{{ temp_backup_dir }}/{{ service_dir_name | replace('-', '_') }}_dump.sql"
